version: '3'
services:
  nginx:
    image: nginx:1.27.0
    container_name: usst_website_nginx
    restart: always
    volumes:
      - /var/jenkins_home/volumes/usst_website/nginx/etc/nginx:/etc/nginx
      - /var/jenkins_home/volumes/usst_website/nginx/usr/share/nginx:/usr/share/nginx
    networks:
      - navsmart_network
    ports:
      - "8080:80"
    depends_on:
      - usst_website_user
      - usst_website_article

  userModule:
    image: usst-website/user:latest
    container_name: usst_website_user
    restart: always
    networks:
      - website_network
    expose:
      - 8081
    depends_on:
      - usst_website_nacos
      - usst_website_mysql

  articleModule:
    image: usst-website/article:latest
    container_name: usst_website_article
    restart: always
    networks:
      - website_network
    expose:
      - 8082
    depends_on:
      - usst_website_nacos
      - usst_website_mysql

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: usst_website_nacos
    networks:
      - navsmart_network
    env_file:
      - nacos_mysql.env
    volumes:
      - /var/jenkins_home/volumes/usst_website/nacos/logs:/home/nacos/logs
    expose:
      - 8848
      - 9848
      - 9849
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.4.2
    container_name: usst_website_mysql
    networks:
      - navsmart_network
    build:
      dockerfile: mysql_dockerfile
    env_file:
      - mysql.env
    expose:
      - 3306
    volumes:
      - /var/jenkins_home/volumes/usst_website/mysql/data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  website_network:
    driver: bridge