version: '3'
services:
  nginx:
    image: usst-website/nginx:latest
    container_name: usst_website_nginx
    restart: always
    volumes:
      - /root/jenkins/jenkins_home/volumes/usst_website/nginx/etc/nginx:/etc/nginx
      # - /root/jenkins/jenkins_home/volumes/usst_website/nginx/usr/share/nginx:/usr/share/nginx
    networks:
      - website_network
    ports:
      - "80:80"
    depends_on:
      - userModule
      - articleModule

  userModule:
    image: usst-website/user:latest
    container_name: usst_website_user
    restart: always
    networks:
      - website_network
    expose:
      - 8081
    depends_on:
      - nacos
      - mysql

  articleModule:
    image: usst-website/article:latest
    container_name: usst_website_article
    restart: always
    networks:
      - website_network
    expose:
      - 8082
    depends_on:
      - nacos
      - mysql

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: usst_website_nacos
    networks:
      - website_network
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - NACOS_AUTH_IDENTITY_KEY=2222
      - NACOS_AUTH_IDENTITY_VALUE=2xxx
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - /root/jenkins/jenkins_home/volumes/usst_website/nacos/logs:/home/nacos/logs
      - /root/jenkins/jenkins_home/volumes/usst_website/nacos/conf:/home/nacos/conf
      - /root/jenkins/jenkins_home/volumes/usst_website/nacos/data:/home/nacos/data
    expose:
      - 8848
      - 9848
      - 9849
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.4.2
    container_name: usst_website_mysql
    networks:
      - website_network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nacos
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
      - LANG=C.UTF-8
    expose:
      - 3306
    volumes:
      - /root/jenkins/jenkins_home/volumes/usst_website/mysql/data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  website_network:
    driver: bridge